# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  sentry_enabled: false
  deepl_api_key: <%= ENV["DEEPL_API_KEY"] %>
  omniauth:
    facebook:
      # It must be a boolean. Remember ENV variables doesn't support booleans.
      enabled: true
      app_id: <%= ENV["OMNIAUTH_FACEBOOK_APP_ID"] %>
      app_secret: <%= ENV["OMNIAUTH_FACEBOOK_APP_SECRET"] %>
    twitter:
      enabled: false
      api_key: <%= ENV["OMNIAUTH_TWITTER_API_KEY"] %>
      api_secret: <%= ENV["OMNIAUTH_TWITTER_API_SECRET"] %>
    google_oauth2:
      enabled: true
      client_id: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_ID"] %>
      client_secret: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_SECRET"] %>
    saml:
      enabled: true
      idp_sso_target_url: <%= ENV["OMNIAUTH_SAML_IDP_SSO_TARGET_URL"] %>
      assertion_consumer_service_url: <%= ENV["OMNIAUTH_SAML_ASSERTION_CONSUMER_SERVICE_URL"] %>
      authn_context: <%= ENV["OMNIAUTH_SAML_AUTHN_CONTEXT"] %>
      issuer: <%= ENV["OMNIAUTH_SAML_ISSUER"] %>
      protocol_binding: <%= ENV["OMNIAUTH_SAML_PROTOCOL_BINDING"] %>
      authn_context_comparison: <%= ENV["OMNIAUTH_SAML_AUTHN_CONTEXT_COMPARISON"] %>
      authn_force: <%= ENV["OMNIAUTH_SAML_AUTHN_FORCE"] %>
      idp_slo_target_url: <%= ENV["OMNIAUTH_SAML_IDP_SLO_TARGET_URL"] %>
      name_identifier_format: <%= ENV["OMNIAUTH_SAML_NAME_IDENTIFIER_FORMAT"] %>
      uid_attribute:  <%= ENV["OMNIAUTH_SAML_UID_ATTRIBUTE"] %>
      idp_cert_fingerprint: <%= ENV["OMNIAUTH_SAML_IDP_CERT_FINGERPRINT"] %>
      idp_cert: <%= ENV["OMNIAUTH_SAML_IDP_CERT"] %>
  geocoder:
    here_app_id: <%= ENV["GEOCODER_LOOKUP_APP_ID"] %>
    here_app_code: <%= ENV["GEOCODER_LOOKUP_APP_CODE"] %>


development:
  <<: *default
  secret_key_base: 45bbff55ac38e2cd96a744c571edf3b2b74f22f2e4ef1c0073876de7c3473d163a0cba512f5924828264a5decb804a41dc6be03c401b891dcfdf4a1a646fc41c
test:
  <<: *default
  secret_key_base: 1157d2bf9b462c71d02f6f1c4072c7427eb92c7c56ba8564b0d690e7ff9ac45a36ed8f6ba1755222f79f2a8a1d59ca2c30c3d8e2194855a500462fa9b07386c7
  omniauth:
    facebook:
      enabled: true
    twitter:
      enabled: true
    google_oauth2:
      enabled: true

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || "2a8dd0b1efc6a14e15eca17ec12089ca01fee43beb54f148f834f6e5f875c68817a6f189a9b14640918099dc0f4a1c7f9c5ab64c52dcf4079a83444a36fb974b" %>
  sendgrid: <%= !ENV["SENDGRID_USERNAME"].blank? %>
  smtp_username: <%= ENV["SMTP_USERNAME"] || ENV["SENDGRID_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] || ENV["SENDGRID_PASSWORD"] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] || "smtp.sendgrid.net" %>
  smtp_domain: <%= ENV["SMTP_DOMAIN"] || "herokuapp.com" %>
  smtp_port: "587"
  smtp_starttls_auto: true
  smtp_authentication: "plain"
  sentry_enabled: true
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
