# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  admin_sign_in_path: "admin_sign_in"
  helpscout:
    enabled: <%= !ENV["HELP_SCOUT_BEACON_ID_MAIN"].blank? %>
    main: <%= ENV["HELP_SCOUT_BEACON_ID_MAIN"] %>
    fallback: <%= ENV["HELP_SCOUT_BEACON_ID_FALLBACK"] %>
  hotjar:
    enabled: <%= !ENV["HOTJAR_SITE_ID"].blank? %>
    site_id: <%= ENV["HOTJAR_SITE_ID"] %>
  scaleway:
    id: <%= ENV["SCALEWAY_ID"] %>
    token: <%= ENV["SCALEWAY_TOKEN"] %>
    bucket_name: <%= ENV["SCALEWAY_BUCKET_NAME"] %>
  omniauth:
    france_connect_uid:
      enabled: true
      icon_path: "france-connect-logo.svg"
      button_path: "FCboutons-10@2x.png"
      provider_name: "FranceConnect \"Signataire\""
      site: <%= ENV["FRANCE_CONNECT_UID_SITE"] %>
      client_id: <%= ENV["FRANCE_CONNECT_UID_CLIENT_ID"] %>
      client_secret: <%= ENV["FRANCE_CONNECT_UID_CLIENT_SECRET"] %>
      end_session_endpoint: <%= ENV["OMNIAUTH_FRANCE_CONNECT_UID_END_SESSION_ENDPOINT"] %>
      minimum_age: <%= ENV["OMNIAUTH_FRANCE_CONNECT_UID_MINIMUM_AGE"] %>
      # redirect_uri: "https://decidim.local.osp.cat/users/auth/france_connect_uid/callback"
    france_connect_profile:
      enabled: true
      icon_path: "france-connect-logo.svg"
      button_path: "FCboutons-10@2x.png"
      provider_name: "FranceConnect \"Auteur\""
      site: <%= ENV["FRANCE_CONNECT_PROFILE_SITE"] %>
      client_id: <%= ENV["FRANCE_CONNECT_PROFILE_CLIENT_ID"] %>
      client_secret: <%= ENV["FRANCE_CONNECT_PROFILE_CLIENT_SECRET"] %>
      end_session_endpoint: <%= ENV["OMNIAUTH_FRANCE_CONNECT_PROFILE_END_SESSION_ENDPOINT"] %>
      minimum_age: <%= ENV["OMNIAUTH_FRANCE_CONNECT_PROFILE_MINIMUM_AGE"] %>
      # redirect_uri: "https://decidim.local.osp.cat/users/auth/france_connect_profile/callback"
  geocoder:
    here_app_id: <%= ENV["HERE_APP_ID"] %>
    here_app_code: <%= ENV["HERE_APP_CODE"] %>
  sentry:
    enabled: false
    dsn: <%= ENV["SENTRY_DSN"] %>
    js_version: "4.6.4"
  etherpad:
    server: <%= ENV["ETHERPAD_SERVER"] %>
    api_key: <%= ENV["ETHERPAD_API_KEY"] %>
    api_version: "1.2.1"

development:
  <<: *default
  secret_key_base: f29d4cdbacaff2279b8580b025878a9e591846de1e9907691165f86e85384d73b4885e6f96719b61fd49a60d2bf12b4342e0e2bd2be407cee2f39356d71019de

test:
  <<: *default
  secret_key_base: a3a8d9cb9ca3e682e2552e8d0c5ad88069339c136338174c5c76ef3970249df6cd18f3220e527b1956d01d9871f89064bad5955e5d8e40e2a39c4e4f5c11eee0
  omniauth:
    facebook:
      enabled: true
    twitter:
      enabled: true
    google_oauth2:
      enabled: true

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  # admin_sign_in_path: <%= ENV["DECIDIM_ADMIN_SIGN_IN_PATH"] %>
  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] %>
  smtp_domain: <%= ENV["SMTP_DOMAIN"] %>
  smtp_port: <%= ENV["SMTP_PORT"] %>
  smtp_starttls_auto: true
  smtp_authentication: "plain"
